In [ ]:
import requests

url = "https://appstore-scrapper-api.p.rapidapi.com/v1/app-store-api/search?num=1&lang=en&query=sleep&country=us"
headers = {
    "X-RapidAPI-Key": "",
    "X-RapidAPI-Host": "appstore-scrapper-api.p.rapidapi.com"
}
response = requests.get(url, headers=headers)
data = response.json()

In [ ]:
data

[{'id': 320606217,
  'appId': 'com.lexwarelabs.goodmorning',
  'title': 'Sleep Cycle - Tracker & Sounds',
  'url': 'https://apps.apple.com/us/app/sleep-cycle-tracker-sounds/id320606217?uo=4',
  'description': "Start every day right with Sleep Cycle’s intelligent alarm clock. It wakes you gently during your lightest sleep phase, helping you feel energized. Get a detailed analysis of your sleep patterns, detect sounds like snoring and coughing, and enjoy premium features like relaxing sleep sounds, a sleep story library, and more!\n\n3 REASONS YOU’LL LOVE SLEEP CYCLE:\n\n1. Wake up feeling refreshed: Achieve your sleep goals by waking up naturally during your lightest sleep phase.\n2. Track your progress: Monitor your sleep habits and reach your sleep goals with detailed tracking and analysis.\n3. No wearables needed: Simply place your phone on your nightstand, and Sleep Cycle uses sound analysis to track your sleep without a need for additional wearables or gadgets.\n\nSTART A BETTER SLEEP ROUTINE:\n\nSleep Cycle is your companion for building lasting, healthy sleep habits that support your everyday life:\n\n1. Track Your Sleep Score: Sleep Cycle gives you a sleep score every morning based on your sleep quality, helping you understand how well you’ve rested and what you can do to improve.\n2. Set Sleep Goals: Define your sleep goals and use Sleep Cycle’s insights to achieve them. Whether it’s more deep sleep, better wake-up mood, or consistent sleep patterns, Sleep Cycle guides you along the way.\n\n\nSLEEP TRACKER FEATURES:\n\n√ Sleep analysis with Sleep Cycle patented sound technology or accelerometer\n√ Detailed sleep statistics and daily sleep graphs\n√ New! Enhanced sleep stage tracking with detailed insights into all your sleep stages.\n√ Fully integrated with Apple Health, exchanging sleep analysis\n√ Carefully selected alarm melodies\n√ Snooze by shaking or double-tapping the phone lightly\n√ Customizable wake-up window. From instant (regular alarm clock), up to 45 minutes\n√ Sound recorder & Trends - Capture snoring, sleep talking and other sounds and view your trends\n√ Who’s snoring? Know if it is you or a partner snoring for a more accurate sleep analysis\n√ Cough Radar & Coughing - Track and compare your nightly coughing levels with local data to make informed decisions for your health\n√ Sleep Aid - our library of sleep stories, relaxation guides and calm sleep sounds, specially designed to help you fall asleep easier. (Mindfulness & meditation)\n√ Trends – gather long-term trends on your sleep patterns\n√ Comparison Data - Compare your sleep patterns to world sleep statistics\n√ Weather & Sleep - See how different types of weather affect your sleep quality\n√ Sleep Notes - See how events such as drinking coffee, stress, working out or eating late affect your sleep quality\n√ Wake-up Mood - See how Sleep Cycle affects your wake-up mood over time\n√ Online Backup - Secure your sleep data online\n√ Data Export – Download sleep data to Excel for detailed analysis\n√ Philips HUE Light Bulb Support - Simulate a natural sunrise to give you an even softer wake-up\n\nJOIN OVER 1 MILLION USERS\nOver 1 million users have already made better sleep their goal. Join them and start tracking your sleep with Sleep Cycle today. Achieve your sleep goals and wake up feeling your best.\n\n-------------------------\n\nREQUIREMENTS\n\nAbility to charge your phone by the bed.\nAbility to place your phone near the bed, such as on a nightstand table or on the floor.\n\n-------------------------\n\nThe Premium subscription will be charged to your iTunes account after the purchase. The subscription will be auto-renewed 24 hours before the subscription period ends with the same kind of subscription you already bought at the same price. To avoid automatic renewal, you must cancel the subscription at least 24 hours before it expires. You can manage or cancel your auto-renewable subscription by entering the user settings in iTunes after the purchase. It's not possible to abort the subscription during the time it's active. Any unused portion of a free trial period, if offered, will be forfeited when you purchase the premium subscription.\n\nTerms and Privacy: https://www.sleepcycle.com/privacy-policy/",
  'icon': 'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/e1/fe/c1/e1fec1f0-21d3-40e2-8943-81060bf2c681/AppIcon-0-0-1x_U007epad-0-1-0-85-220.png/512x512bb.jpg',
  'genres': ['Health & Fitness', 'Lifestyle'],
  'genreIds': ['6013', '6012'],
  'primaryGenre': 'Health & Fitness',
  'primaryGenreId': 6013,
  'contentRating': '4+',
  'languages': ['NL',
   'EN',
   'FR',
   'DE',
   'IT',
   'JA',
   'KO',
   'PT',
   'RU',
   'ZH',
   'ES',
   'SV',
   'ZH',
   'TR'],
  'size': '415750144',
  'requiredOsVersion': '15.0',
  'released': '2009-07-23T23:52:39Z',
  'updated': '2025-09-22T06:52:16Z',
  'releaseNotes': 'Bug fixes and improvements.',
  'version': '6.25.37',
  'price': 0,
  'currency': 'USD',
  'free': True,
  'developerId': 320606220,
  'developer': 'Sleep Cycle AB',
  'developerUrl': 'https://apps.apple.com/us/developer/sleep-cycle-ab/id320606220?uo=4',
  'developerWebsite': 'https://www.sleepcycle.com',
  'score': 4.6433,
  'reviews': 12857,
  'currentVersionScore': 4.6433,
  'currentVersionReviews': 12857,
  'screenshots': ['https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/85/de/c5/85dec5ed-9de6-c7b4-5874-ad643a031b8f/6388991e-7c0d-4d0d-8ce6-f1a71fb6bfac_SC_-_iPhone_-_5.5_-_1.png/392x696bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/a7/d4/2e/a7d42ef0-6f15-37d7-8d58-f51f1e7f18a2/9ad20ca3-3604-435a-b52b-7ad8a2c5c336_SC_-_iPhone_-_5.5_-_2.png/392x696bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/e1/34/5a/e1345a44-6d32-e5f4-83e7-6c816111311d/496a7b31-83ef-4ab7-a4ef-d0e7d13e2a19_SC_-_iPhone_-_5.5_-_3.png/392x696bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/2d/67/4b/2d674b09-9a44-d4bf-a9ea-5ab47f844020/e3e1f6e4-06d3-4407-a3e0-7a858ca7a00f_SC_-_iPhone_-_5.5_-_4.png/392x696bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/ee/d6/5d/eed65d52-e481-8abf-69b8-f93fbb6a02cb/4e1a8849-6f02-44d9-80f6-749d189a47f5_SC_-_iPhone_-_5.5_-_5.png/392x696bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/50/d0/3e/50d03e9e-c02a-d9f2-59f9-2cb5bd5829e6/716a4c6e-4b7d-45b5-bb88-cd0fbd4b147e_SC_-_iPhone_-_5.5_-_6.png/392x696bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/8f/71/d6/8f71d673-ee92-dee6-a439-3e2c6f4549ae/d8c2066a-ffc3-4af9-bb2a-f808af6cebc5_SC_-_iPhone_-_5.5_-_7.png/392x696bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/7f/00/8d/7f008dd2-9a63-bbec-de71-ed6d8c1ccecf/30dac03a-fd82-49bd-bff9-65cc8f990ed4_SC_-_iPhone_-_5.5_-_8.png/392x696bb.png'],
  'ipadScreenshots': ['https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/18/1f/d2/181fd25f-95f1-fdc0-35d8-b03c4618de15/f706957a-db7a-4ce9-937e-f08c8a275a5e_SC_iPad_iOS_2048x2732px_01.png/576x768bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/c9/05/26/c9052605-4d18-0571-ab63-ad72b44c2b51/f2cf43a7-619e-4879-ba35-398a32d3eb02_SC_iPad_iOS_2048x2732px_02.png/576x768bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/b2/42/8a/b2428ab6-df96-e3ea-0449-aa8cc4511e79/7264bb5d-5cbc-4377-8567-de9c182972e1_SC_iPad_iOS_2048x2732px_03.png/576x768bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/a3/12/52/a31252c5-5f63-e97f-1e0c-a9656c83921f/92aa3898-ebd7-4a57-87d3-23a1328c8504_SC_iPad_iOS_2048x2732px_04.png/576x768bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/47/6e/10/476e10a4-2a73-f0bd-47ea-40b217193ef8/4b21719e-517e-44b2-8e16-adaa0bde28e5_SC_iPad_iOS_2048x2732px_05.png/576x768bb.png',
   'https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/df/45/42/df454234-8f53-78e9-206e-5db34540d3b4/e2d0a48e-6365-469e-ab00-28dbbb84ea3c_SC_iPad_iOS_2048x2732px_06.png/576x768bb.png'],
  'appletvScreenshots': [],
  'supportedDevices': ['iPhone5s-iPhone5s',
   'iPadAir-iPadAir',
   'iPadAirCellular-iPadAirCellular',
   'iPadMiniRetina-iPadMiniRetina',
   'iPadMiniRetinaCellular-iPadMiniRetinaCellular',
   'iPhone6-iPhone6',
   'iPhone6Plus-iPhone6Plus',
   'iPadAir2-iPadAir2',
   'iPadAir2Cellular-iPadAir2Cellular',
   'iPadMini3-iPadMini3',
   'iPadMini3Cellular-iPadMini3Cellular',
   'iPodTouchSixthGen-iPodTouchSixthGen',
   'iPhone6s-iPhone6s',
   'iPhone6sPlus-iPhone6sPlus',
   'iPadMini4-iPadMini4',
   'iPadMini4Cellular-iPadMini4Cellular',
   'iPadPro-iPadPro',
   'iPadProCellular-iPadProCellular',
   'iPadPro97-iPadPro97',
   'iPadPro97Cellular-iPadPro97Cellular',
   'iPhoneSE-iPhoneSE',
   'iPhone7-iPhone7',
   'iPhone7Plus-iPhone7Plus',
   'iPad611-iPad611',
   'iPad612-iPad612',
   'iPad71-iPad71',
   'iPad72-iPad72',
   'iPad73-iPad73',
   'iPad74-iPad74',
   'iPhone8-iPhone8',
   'iPhone8Plus-iPhone8Plus',
   'iPhoneX-iPhoneX',
   'iPad75-iPad75',
   'iPad76-iPad76',
   'iPhoneXS-iPhoneXS',
   'iPhoneXSMax-iPhoneXSMax',
   'iPhoneXR-iPhoneXR',
   'iPad812-iPad812',
   'iPad834-iPad834',
   'iPad856-iPad856',
   'iPad878-iPad878',
   'Watch4-Watch4',
   'iPadMini5-iPadMini5',
   'iPadMini5Cellular-iPadMini5Cellular',
   'iPadAir3-iPadAir3',
   'iPadAir3Cellular-iPadAir3Cellular',
   'iPodTouchSeventhGen-iPodTouchSeventhGen',
   'iPhone11-iPhone11',
   'iPhone11Pro-iPhone11Pro',
   'iPadSeventhGen-iPadSeventhGen',
   'iPadSeventhGenCellular-iPadSeventhGenCellular',
   'iPhone11ProMax-iPhone11ProMax',
   'iPhoneSESecondGen-iPhoneSESecondGen',
   'iPadProSecondGen-iPadProSecondGen',
   'iPadProSecondGenCellular-iPadProSecondGenCellular',
   'iPadProFourthGen-iPadProFourthGen',
   'iPadProFourthGenCellular-iPadProFourthGenCellular',
   'iPhone12Mini-iPhone12Mini',
   'iPhone12-iPhone12',
   'iPhone12Pro-iPhone12Pro',
   'iPhone12ProMax-iPhone12ProMax',
   'iPadAir4-iPadAir4',
   'iPadAir4Cellular-iPadAir4Cellular',
   'iPadEighthGen-iPadEighthGen',
   'iPadEighthGenCellular-iPadEighthGenCellular',
   'iPadProThirdGen-iPadProThirdGen',
   'iPadProThirdGenCellular-iPadProThirdGenCellular',
   'iPadProFifthGen-iPadProFifthGen',
   'iPadProFifthGenCellular-iPadProFifthGenCellular',
   'iPhone13Pro-iPhone13Pro',
   'iPhone13ProMax-iPhone13ProMax',
   'iPhone13Mini-iPhone13Mini',
   'iPhone13-iPhone13',
   'iPadMiniSixthGen-iPadMiniSixthGen',
   'iPadMiniSixthGenCellular-iPadMiniSixthGenCellular',
   'iPadNinthGen-iPadNinthGen',
   'iPadNinthGenCellular-iPadNinthGenCellular',
   'iPhoneSEThirdGen-iPhoneSEThirdGen',
   'iPadAirFifthGen-iPadAirFifthGen',
   'iPadAirFifthGenCellular-iPadAirFifthGenCellular',
   'iPhone14-iPhone14',
   'iPhone14Plus-iPhone14Plus',
   'iPhone14Pro-iPhone14Pro',
   'iPhone14ProMax-iPhone14ProMax',
   'iPadTenthGen-iPadTenthGen',
   'iPadTenthGenCellular-iPadTenthGenCellular',
   'iPadPro11FourthGen-iPadPro11FourthGen',
   'iPadPro11FourthGenCellular-iPadPro11FourthGenCellular',
   'iPadProSixthGen-iPadProSixthGen',
   'iPadProSixthGenCellular-iPadProSixthGenCellular',
   'iPhone15-iPhone15',
   'iPhone15Plus-iPhone15Plus',
   'iPhone15Pro-iPhone15Pro',
   'iPhone15ProMax-iPhone15ProMax',
   'iPadAir11M2-iPadAir11M2',
   'iPadAir11M2Cellular-iPadAir11M2Cellular',
   'iPadAir13M2-iPadAir13M2',
   'iPadAir13M2Cellular-iPadAir13M2Cellular',
   'iPadPro11M4-iPadPro11M4',
   'iPadPro11M4Cellular-iPadPro11M4Cellular',
   'iPadPro13M4-iPadPro13M4',
   'iPadPro13M4Cellular-iPadPro13M4Cellular',
   'iPhone16-iPhone16',
   'iPhone16Plus-iPhone16Plus',
   'iPhone16Pro-iPhone16Pro',
   'iPhone16ProMax-iPhone16ProMax',
   'iPadMiniA17Pro-iPadMiniA17Pro',
   'iPadMiniA17ProCellular-iPadMiniA17ProCellular',
   'iPhone16e-iPhone16e',
   'iPadA16-iPadA16',
   'iPadA16Cellular-iPadA16Cellular',
   'iPadAir11M3-iPadAir11M3',
   'iPadAir11M3Cellular-iPadAir11M3Cellular',
   'iPadAir13M3-iPadAir13M3',
   'iPadAir13M3Cellular-iPadAir13M3Cellular',
   'iPhone17Pro-iPhone17Pro',
   'iPhone17ProMax-iPhone17ProMax',
   'iPhone17-iPhone17',
   'iPhoneAir-iPhoneAir']}]

In [ ]:
import pandas as pd

df = pd.DataFrame(data)
df = df.rename(columns={
    'title': 'App',
    'score': 'Rating',
    'reviews': 'Reviews',
    'size': 'Size',
    'price': 'Price($)',
    'contentRating': 'Content Rating',
    'genres': 'Genres',
    'version': 'Current Version',
    'requiredOsVersion': 'Required Version',
    'updated': 'Last Updated'
})

# Keep only the requested columns
requested_columns = ['App', 'Rating', 'Reviews', 'Size', 'Price($)', 'Content Rating', 'Genres', 'Current Version', 'Required Version', 'Last Updated']
df = df[requested_columns]

display(df)

,App,Rating,Reviews,Size,Price($),Content Rating,Genres,Current Version,Required Version,Last Updated
0,Sleep Cycle - Tracker & Sounds,4.6433,12857,415750144,0,4+,"[Health & Fitness, Lifestyle]",6.25.37,15.0,2025-09-22T06:52:16Z

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               1 non-null      object
 1   Rating            1 non-null      float64
 2   Reviews           1 non-null      int64
 3   Size              1 non-null      object
 4   Price($)          1 non-null      int64
 5   Content Rating    1 non-null      object
 6   Genres            1 non-null      object
 7   Current Version   1 non-null      object
 8   Required Version  1 non-null      object
 9   Last Updated      1 non-null      object
dtypes: float64(1), int64(2), object(7)
memory usage: 212.0+ bytes

In [ ]:
import requests
import pandas as pd

url = "https://appstore-scrapper-api.p.rapidapi.com/v1/app-store-api/search?num=10&lang=en&query=sleep&country=us"
headers = {
    "X-RapidAPI-Key": "",
    "X-RapidAPI-Host": "appstore-scrapper-api.p.rapidapi.com"
}
response = requests.get(url, headers=headers)
temp_data = response.json()

temp_df = pd.DataFrame(temp_data)
temp_df = temp_df.rename(columns={
    'title': 'App',
    'score': 'Rating',
    'reviews': 'Reviews',
    'size': 'Size',
    'price': 'Price($)',
    'contentRating': 'Content Rating',
    'genres': 'Genres',
    'version': 'Current Version',
    'requiredOsVersion': 'Required Version',
    'updated': 'Last Updated'
})

requested_columns = ['App', 'Rating', 'Reviews', 'Size', 'Price($)', 'Content Rating', 'Genres', 'Current Version', 'Required Version', 'Last Updated']
temp_df = temp_df[requested_columns]

display(temp_df)

,App,Rating,Reviews,Size,Price($),Content Rating,Genres,Current Version,Required Version,Last Updated
0,Sleep Cycle - Tracker & Sounds,4.64250,12775,415750144,0.00,4+,"[Health & Fitness, Lifestyle]",6.25.37,15.0,2025-09-22T06:52:16Z
1,"ShutEye®: Sleep Tracker, Sound",4.76975,338430,451469312,0.00,4+,[Health & Fitness],3.2.0,15.0,2025-08-30T00:44:21Z
2,BetterSleep: Relax and Sleep,4.74964,383571,385760256,0.00,4+,[Health & Fitness],25.17,15.0,2025-09-15T10:10:06Z
3,SleepWatch - Top Sleep Tracker,4.65391,328600,417311744,0.00,4+,"[Health & Fitness, Lifestyle]",8.5.12,15.0,2025-08-23T14:25:30Z
4,SnailSleep-Tracker & Sound,4.71820,401,134616064,0.00,12+,"[Health & Fitness, Lifestyle]",5.1.1,13.0,2025-09-24T09:43:28Z
5,Calm,4.77501,1903128,181463040,0.00,4+,"[Health & Fitness, Lifestyle]",6.80,16.0,2025-09-25T07:15:53Z
6,Pillow: Sleep Tracker,4.37676,94630,682300416,0.00,12+,"[Health & Fitness, Lifestyle]",6.1.1,16.0,2025-09-20T05:21:30Z
7,"Sleep Sounds White Noise, Rain",4.75813,34192,75463680,0.00,4+,[Health & Fitness],1.4.2,10.0,2024-03-04T20:06:55Z
8,RISE: Sleep Tracker,4.68558,42205,207886336,0.00,12+,"[Health & Fitness, Productivity]",1.537.0,15.1,2025-09-22T12:26:22Z
9,AutoSleep Track Sleep on Watch,4.70688,59459,47645696,8.99,4+,"[Health & Fitness, Medical]",6.14,11.0,2024-12-08T15:08:49Z

In [9]:
googledf = pd.read_csv('cleaned_googleplaystore.csv')

In [10]:
googledf.head()

,App,Category,Rating,Size,Installs,Type,Price($),Content Rating,Genres,Current Ver,Android Ver,Reviews,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,19M,10000,Free,0.0,Everyone,Art & Design,1.0.0,4.0.3 and up,159,2018-01-07
1,Coloring book moana,ART_AND_DESIGN,3.9,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0.0,4.0.3 and up,967,2018-01-15
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,8.7M,5000000,Free,0.0,Everyone,Art & Design,1.2.4,4.0.3 and up,87510,2018-08-01
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,25M,50000000,Free,0.0,Teen,Art & Design,Varies with device,4.2 and up,215644,2018-06-08
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,1.1,4.4 and up,967,2018-06-20

In [11]:
unique_categories = googledf['Category'].unique()
print(unique_categories[:20])

['ART_AND_DESIGN' 'AUTO_AND_VEHICLES' 'BEAUTY' 'BOOKS_AND_REFERENCE'
 'BUSINESS' 'COMICS' 'COMMUNICATION' 'DATING' 'EDUCATION' 'ENTERTAINMENT'
 'EVENTS' 'FINANCE' 'FOOD_AND_DRINK' 'HEALTH_AND_FITNESS' 'HOUSE_AND_HOME'
 'LIBRARIES_AND_DEMO' 'LIFESTYLE' 'GAME' 'FAMILY' 'MEDICAL']

# Task
Create a dataframe by iterating through 20 unique values of the 'Category' column from the dataframe `googledf`, using each category as a query parameter in a RapidAPI call with `num=50`. Implement rate limiting and retry logic for the API calls. The resulting dataframe should have the same columns as the original `googledf` dataframe.

## Define the api call function

### Subtask:
Create a function to make API calls with rate limiting and retry logic.

**Reasoning**:
Define a function to handle API calls with rate limiting and retry logic as per the instructions.

In [12]:
import time

def call_app_store_api(category, api_key, num_results=50, max_retries=3, initial_delay=1):
    """
    Makes an API call to the App Store scrapper API with rate limiting and retry logic.

    Args:
        category (str): The app category to search for.
        api_key (str): Your RapidAPI key.
        num_results (int): The number of results to request (default is 50).
        max_retries (int): The maximum number of retries for API calls (default is 3).
        initial_delay (int): The initial delay in seconds before retrying (default is 1).

    Returns:
        list: A list of dictionaries containing the API response data, or an empty list if the call fails after retries.
    """
    base_url = "https://appstore-scrapper-api.p.rapidapi.com/v1/app-store-api/search"
    url = f"{base_url}?num={num_results}&lang=en&query={category}&country=us"
    headers = {
        "X-RapidAPI-Key": api_key,
        "X-RapidAPI-Host": "appstore-scrapper-api.p.rapidapi.com"
    }

    for retry_count in range(max_retries):
        try:
            response = requests.get(url, headers=headers)
            response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)

            if response.status_code == 200:
                return response.json()

        except requests.exceptions.HTTPError as e:
            if response.status_code == 429:
                print(f"Rate limit exceeded for category '{category}'. Retrying in {initial_delay * (2**retry_count)} seconds...")
                time.sleep(initial_delay * (2**retry_count))
            else:
                print(f"HTTP error for category '{category}': {e}")
                break
        except requests.exceptions.RequestException as e:
            print(f"Request error for category '{category}': {e}")
            break

    print(f"Failed to retrieve data for category '{category}' after {max_retries} retries.")
    return []

## Iterate through categories and fetch data

### Subtask:
Loop through the unique categories, call the API for each category using the function created in step 1, and collect the results.

**Reasoning**:
I need to iterate through the first 20 unique categories from `googledf`, call the API function for each, and collect the results in a list.

In [ ]:
unique_categories = googledf['Category'].unique()
selected_categories = unique_categories[:20]
all_app_data = []

# Replace with your actual RapidAPI key
rapidapi_key = ""

for category in selected_categories:
    print(f"Fetching data for category: {category}")
    category_data = call_app_store_api(category, rapidapi_key, num_results=50)
    all_app_data.extend(category_data)

print(f"Collected data for {len(all_app_data)} apps.")

Fetching data for category: ART_AND_DESIGN
Fetching data for category: AUTO_AND_VEHICLES
Fetching data for category: BEAUTY
Fetching data for category: BOOKS_AND_REFERENCE
Fetching data for category: BUSINESS
Fetching data for category: COMICS
Fetching data for category: COMMUNICATION
Fetching data for category: DATING
Fetching data for category: EDUCATION
Fetching data for category: ENTERTAINMENT
Fetching data for category: EVENTS
Fetching data for category: FINANCE
Fetching data for category: FOOD_AND_DRINK
Fetching data for category: HEALTH_AND_FITNESS
Fetching data for category: HOUSE_AND_HOME
Fetching data for category: LIBRARIES_AND_DEMO
Fetching data for category: LIFESTYLE
Fetching data for category: GAME
Fetching data for category: FAMILY
Fetching data for category: MEDICAL
Collected data for 1000 apps.

## Process and combine data

### Subtask:
Convert the collected data into a pandas DataFrame and ensure it has the desired columns.

**Reasoning**:
Convert the collected data into a pandas DataFrame and ensure it has the desired columns by renaming columns, selecting relevant columns, adding missing columns with placeholder values, and concatenating with the existing googledf. Finally, display the head and info of the combined dataframe.

In [19]:
new_df = pd.DataFrame(all_app_data)

new_df = new_df.rename(columns={
    'title': 'App',
    'score': 'Rating',
    'reviews': 'Reviews',
    'size': 'Size',
    'price': 'Price($)',
    'contentRating': 'Content Rating',
    'genres': 'Genres',
    'version': 'Current Version',
    'requiredOsVersion': 'Required Version',
    'updated': 'Last Updated'
})

desired_columns = ['App', 'Rating', 'Reviews', 'Size', 'Price($)', 'Content Rating', 'Genres', 'Current Version', 'Required Version', 'Last Updated']
new_df = new_df[[col for col in new_df.columns if col in desired_columns]]

# # Add missing columns with placeholder values
# for col in ['Category', 'Installs', 'Type']:
#     if col not in new_df.columns:
#         new_df[col] = 'N/A'

# # Map categories to apps (this assumes the order of data returned matches the order of categories called)
# category_list = []
# for i, category in enumerate(selected_categories):
#     category_list.extend([category] * len(all_app_data[i*50:(i+1)*50]))

# # Ensure category_list and new_df have the same number of rows
# if len(category_list) == len(new_df):
#     new_df['Category'] = category_list
# else:
#     print("Warning: The number of collected apps does not match the expected count based on categories. Category mapping may be incorrect.")


display(new_df.head())
display(new_df.info())

,App,Genres,Content Rating,Size,Required Version,Last Updated,Current Version,Price($),Rating,Reviews
0,Graphic Design & Logo Creator,"[Graphics & Design, Photo & Video]",4+,170781696,17.0,2025-09-25T13:46:19Z,12.9,0.0,4.51858,8581
1,Smartist: Art Preview on Wall,"[Photo & Video, Graphics & Design]",4+,261573632,16.0,2025-09-07T16:55:25Z,1.6.10,0.0,4.77596,8320
2,Nail Designs - Manicures & Art,"[Lifestyle, Entertainment]",4+,52657152,18.5,2025-08-27T15:58:43Z,5.02,0.0,3.95838,2499
3,Tenada: Photo & Graphic Design,"[Graphics & Design, Photo & Video]",4+,218086400,14.0,2025-09-09T05:20:41Z,5.4.9,0.0,4.77688,1479
4,Sketch Pro: Draw & Create Art,"[Graphics & Design, Productivity]",4+,366343168,13.0,2025-09-26T07:15:46Z,2.0.1,0.0,4.71448,6511

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               1000 non-null   object
 1   Genres            1000 non-null   object
 2   Content Rating    1000 non-null   object
 3   Size              1000 non-null   object
 4   Required Version  1000 non-null   object
 5   Last Updated      1000 non-null   object
 6   Current Version   1000 non-null   object
 7   Price($)          1000 non-null   float64
 8   Rating            1000 non-null   float64
 9   Reviews           1000 non-null   int64
dtypes: float64(2), int64(1), object(7)
memory usage: 78.3+ KB

None

In [20]:
duplicates = new_df[new_df.duplicated(subset=['App'], keep=False)]

if not duplicates.empty:
    print("Duplicate rows found based on the 'App' column:")
    display(duplicates.sort_values(by='App'))
else:
    print("No duplicate rows found based on the 'App' column.")

Duplicate rows found based on the 'App' column:

,App,Genres,Content Rating,Size,Required Version,Last Updated,Current Version,Price($),Rating,Reviews
759,Amazon Kindle,[Books],12+,182419456,16.0,2025-09-25T03:23:45Z,7.42.1,0.0,4.85710,5282711
275,Amazon Kindle,[Books],12+,182419456,16.0,2025-09-25T03:23:45Z,7.42.1,0.0,4.85710,5282711
185,Anythink Libraries,"[Books, Reference]",4+,15118336,14.0,2025-08-15T17:57:51Z,2025.08.00,0.0,4.42856,7
781,Anythink Libraries,"[Books, Reference]",4+,15118336,14.0,2025-08-15T17:57:51Z,2025.08.00,0.0,4.42856,7
557,Bloomberg: Business News Daily,"[News, Finance]",4+,62410752,15.6,2025-09-16T16:21:08Z,6.47.0,0.0,4.59276,53546
226,Bloomberg: Business News Daily,"[News, Finance]",4+,62410752,15.6,2025-09-16T16:21:08Z,6.47.0,0.0,4.59276,53546
777,BookBuddy: Book Tracker,"[Books, Reference]",4+,30871552,17.0,2025-08-06T17:57:02Z,9.8.2,0.0,4.83926,12424
153,BookBuddy: Book Tracker,"[Books, Reference]",4+,30871552,17.0,2025-08-06T17:57:02Z,9.8.2,0.0,4.83926,12424
529,BookMyShow | Movies & Events,[Entertainment],4+,109635584,15.0,2025-09-16T14:00:16Z,6.1.6,0.0,4.78228,11938
482,BookMyShow | Movies & Events,[Entertainment],4+,109635584,15.0,2025-09-16T14:00:16Z,6.1.6,0.0,4.78228,11938
240,CNBC: Stock Market & Business,"[News, Finance]",4+,122738688,16.0,2025-09-16T21:28:34Z,7.1.1,0.0,4.71511,628389
560,CNBC: Stock Market & Business,"[News, Finance]",4+,122738688,16.0,2025-09-16T21:28:34Z,7.1.1,0.0,4.71511,628389
554,ChatGPT,"[Productivity, Utilities]",12+,120785920,17.0,2025-09-24T20:07:25Z,1.2025.261,0.0,4.86573,3855074
955,ChatGPT,"[Productivity, Utilities]",12+,120785920,17.0,2025-09-24T20:07:25Z,1.2025.261,0.0,4.86573,3855074
750,CloudLibrary,"[Books, Reference]",4+,166654976,15.0,2025-08-12T14:11:51Z,5.12.2,0.0,4.75019,224032
151,CloudLibrary,"[Books, Reference]",4+,166654976,15.0,2025-08-12T14:11:51Z,5.12.2,0.0,4.75019,224032
219,Coursera: Grow your career,[Education],4+,60305408,17.0,2025-09-15T18:23:06Z,7.20.0,0.0,4.84712,158080
408,Coursera: Grow your career,[Education],4+,60305408,17.0,2025-09-15T18:23:06Z,7.20.0,0.0,4.84712,158080
304,"Discord - Talk, Play, Hang Out","[Social Networking, Games]",17+,220697600,15.1,2025-09-22T18:25:48Z,298.0,0.0,4.70781,3221259
862,"Discord - Talk, Play, Hang Out","[Social Networking, Games]",17+,220697600,15.1,2025-09-22T18:25:48Z,298.0,0.0,4.70781,3221259
466,Duolingo - Language Lessons,"[Education, Social Networking]",4+,514594816,16.0,2025-09-22T17:00:06Z,7.92.0,0.0,4.72991,4535571
401,Duolingo - Language Lessons,"[Education, Social Networking]",4+,514594816,16.0,2025-09-22T17:00:06Z,7.92.0,0.0,4.72991,4535571
878,Episode - Choose Your Story,"[Games, Role Playing, Simulation, Entertainment]",12+,490526720,15.0,2025-08-18T20:02:13Z,26.40,0.0,4.65484,2791678
926,Episode - Choose Your Story,"[Games, Role Playing, Simulation, Entertainment]",12+,490526720,15.0,2025-08-18T20:02:13Z,26.40,0.0,4.65484,2791678
500,Eventbrite,"[Entertainment, Lifestyle]",12+,169712640,15.0,2025-09-10T15:54:29Z,10.27.0,0.0,4.89522,1537013
813,Eventbrite,"[Entertainment, Lifestyle]",12+,169712640,15.0,2025-09-10T15:54:29Z,10.27.0,0.0,4.89522,1537013
825,FamilySearch Tree,"[Reference, Lifestyle]",4+,183580672,17.0,2025-09-24T21:09:30Z,5.2.6,0.0,4.83995,454059
908,FamilySearch Tree,"[Reference, Lifestyle]",4+,183580672,17.0,2025-09-24T21:09:30Z,5.2.6,0.0,4.83995,454059
249,Financial Times: Business News,"[News, Business]",4+,80506880,14.0,2025-09-09T15:26:23Z,1.101,0.0,4.81855,22011
570,Financial Times: Business News,"[News, Business]",4+,80506880,14.0,2025-09-09T15:26:23Z,1.101,0.0,4.81855,22011
212,Fiverr - Freelance Services,"[Business, Lifestyle]",4+,127194112,16.0,2025-09-12T01:58:56Z,3.57.2,0.0,4.91800,548581
841,Fiverr - Freelance Services,"[Business, Lifestyle]",4+,127194112,16.0,2025-09-12T01:58:56Z,3.57.2,0.0,4.91800,548581
952,Full Code Medical Simulation,"[Medical, Education]",17+,95417344,14.0,2025-08-13T20:44:10Z,3.5.1,0.0,4.77353,5599
439,Full Code Medical Simulation,"[Medical, Education]",17+,95417344,14.0,2025-08-13T20:44:10Z,3.5.1,0.0,4.77353,5599
755,Google Play Books & Audiobooks,"[Books, Reference]",4+,88590336,17.0,2025-09-12T14:05:32Z,25.9.0,0.0,4.43152,9580
150,Google Play Books & Audiobooks,"[Books, Reference]",4+,88590336,17.0,2025-09-12T14:05:32Z,25.9.0,0.0,4.43152,9580
895,Hay Day,"[Games, Simulation, Family, Entertainment]",4+,600160256,12.0,2025-09-22T10:01:21Z,1.67.170,0.0,4.69763,613294
931,Hay Day,"[Games, Simulation, Family, Entertainment]",4+,600160256,12.0,2025-09-22T10:01:21Z,1.67.170,0.0,4.69763,613294
321,Khan Academy,[Education],4+,47288320,15.0,2025-04-16T15:55:34Z,8.3.2,0.0,4.56780,97375
400,Khan Academy,[Education],4+,47288320,15.0,2025-04-16T15:55:34Z,8.3.2,0.0,4.56780,97375
974,Lecturio Medical Education,"[Medical, Education]",17+,126852096,15.0,2025-09-17T23:44:55Z,34.1.0,0.0,4.79709,4189
420,Lecturio Medical Education,"[Medical, Education]",17+,126852096,15.0,2025-09-17T23:44:55Z,34.1.0,0.0,4.79709,4189
754,"Libby, the library app","[Books, Entertainment]",4+,12030976,10.0,2025-09-12T13:11:17Z,8.3.1,0.0,4.85271,3868862
277,"Libby, the library app","[Books, Entertainment]",4+,12030976,10.0,2025-09-12T13:11:17Z,8.3.1,0.0,4.85271,3868862
772,Manga Dogs - webtoon reader,"[Books, Entertainment]",17+,84582400,13.0,2025-08-26T00:19:34Z,4.7.9,0.0,4.07285,1757
292,Manga Dogs - webtoon reader,"[Books, Entertainment]",17+,84582400,13.0,2025-08-26T00:19:34Z,4.7.9,0.0,4.07285,1757
803,Meetup: Social Events & Groups,"[Social Networking, Lifestyle]",12+,209107968,15.0,2025-09-24T15:26:22Z,2025.9.20,0.0,4.72621,268401
501,Meetup: Social Events & Groups,"[Social Networking, Lifestyle]",12+,209107968,15.0,2025-09-24T15:26:22Z,2025.9.20,0.0,4.72621,268401
897,The Sims™ FreePlay,"[Games, Simulation, Adventure]",12+,2496528384,15.0,2025-09-11T05:15:12Z,5.95.1,0.0,4.58176,419210
907,The Sims™ FreePlay,"[Games, Simulation, Adventure]",12+,2496528384,15.0,2025-09-11T05:15:12Z,5.95.1,0.0,4.58176,419210
193,Vocabulary - Learn words daily,"[Education, Reference]",4+,227178496,16.0,2025-09-23T16:36:42Z,6.2.0,0.0,4.79940,166681
403,Vocabulary - Learn words daily,"[Education, Reference]",4+,227178496,16.0,2025-09-23T16:36:42Z,6.2.0,0.0,4.79940,166681
300,WhatsApp Messenger,"[Social Networking, Utilities]",12+,239306752,15.1,2025-09-22T15:45:33Z,25.26.72,0.0,4.69194,16514244
216,WhatsApp Messenger,"[Social Networking, Utilities]",12+,239306752,15.1,2025-09-22T15:45:33Z,25.26.72,0.0,4.69194,16514244
519,"Yelp: Food, Services & Reviews","[Food & Drink, Travel]",12+,324849664,17.0,2025-09-22T05:23:35Z,25.38.0,0.0,4.50497,1687192
604,"Yelp: Food, Services & Reviews","[Food & Drink, Travel]",12+,324849664,17.0,2025-09-22T05:23:35Z,25.38.0,0.0,4.50497,1687192
418,Yuno - General knowledge,"[Education, Books]",4+,114149376,16.0,2025-09-22T12:14:22Z,4.9.1,0.0,4.76154,7364
760,Yuno - General knowledge,"[Education, Books]",4+,114149376,16.0,2025-09-22T12:14:22Z,4.9.1,0.0,4.76154,7364

In [21]:
new_df = new_df.drop_duplicates(subset=['App'], keep='first')
print("Duplicate rows removed. The updated DataFrame info is:")
display(new_df.info())

Duplicate rows removed. The updated DataFrame info is:
<class 'pandas.core.frame.DataFrame'>
Index: 971 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               971 non-null    object
 1   Genres            971 non-null    object
 2   Content Rating    971 non-null    object
 3   Size              971 non-null    object
 4   Required Version  971 non-null    object
 5   Last Updated      971 non-null    object
 6   Current Version   971 non-null    object
 7   Price($)          971 non-null    float64
 8   Rating            971 non-null    float64
 9   Reviews           971 non-null    int64
dtypes: float64(2), int64(1), object(7)
memory usage: 83.4+ KB

None

In [22]:
new_df

,App,Genres,Content Rating,Size,Required Version,Last Updated,Current Version,Price($),Rating,Reviews
0,Graphic Design & Logo Creator,"[Graphics & Design, Photo & Video]",4+,170781696,17.0,2025-09-25T13:46:19Z,12.9,0.00,4.51858,8581
1,Smartist: Art Preview on Wall,"[Photo & Video, Graphics & Design]",4+,261573632,16.0,2025-09-07T16:55:25Z,1.6.10,0.00,4.77596,8320
2,Nail Designs - Manicures & Art,"[Lifestyle, Entertainment]",4+,52657152,18.5,2025-08-27T15:58:43Z,5.02,0.00,3.95838,2499
3,Tenada: Photo & Graphic Design,"[Graphics & Design, Photo & Video]",4+,218086400,14.0,2025-09-09T05:20:41Z,5.4.9,0.00,4.77688,1479
4,Sketch Pro: Draw & Create Art,"[Graphics & Design, Productivity]",4+,366343168,13.0,2025-09-26T07:15:46Z,2.0.1,0.00,4.71448,6511
...,...,...,...,...,...,...,...,...,...,...
995,Pocket Pharmacist,"[Medical, Health & Fitness]",17+,49008640,17.6,2025-09-18T17:06:37Z,3.5.41,0.00,4.71326,3749
996,MDLIVE,"[Medical, Health & Fitness]",17+,107270144,13.0,2025-09-12T23:28:38Z,7.6.0,0.00,4.70946,90758
997,98point6 by Transcarent,"[Medical, Health & Fitness]",17+,160053248,15.0,2025-09-19T20:03:11Z,5.18.0,0.00,4.76234,50813
998,Express Scripts,"[Medical, Health & Fitness]",4+,46461952,16.0,2025-08-14T14:49:21Z,12.26.0,0.00,4.75441,373353
999,Critical- Medical Guide,"[Medical, Health & Fitness]",17+,378426368,15.0,2022-08-18T01:17:58Z,33,14.99,4.82580,1062

In [24]:
new_df['Genres'] = new_df['Genres'].apply(lambda x: ', '.join(x))
display(new_df['Genres'])

0      Graphics & Design, Photo & Video
1      Photo & Video, Graphics & Design
2              Lifestyle, Entertainment
3      Graphics & Design, Photo & Video
4       Graphics & Design, Productivity
                     ...
995           Medical, Health & Fitness
996           Medical, Health & Fitness
997           Medical, Health & Fitness
998           Medical, Health & Fitness
999           Medical, Health & Fitness
Name: Genres, Length: 971, dtype: object

In [25]:
display(new_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 971 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               971 non-null    object
 1   Genres            971 non-null    object
 2   Content Rating    971 non-null    object
 3   Size              971 non-null    object
 4   Required Version  971 non-null    object
 5   Last Updated      971 non-null    object
 6   Current Version   971 non-null    object
 7   Price($)          971 non-null    float64
 8   Rating            971 non-null    float64
 9   Reviews           971 non-null    int64
dtypes: float64(2), int64(1), object(7)
memory usage: 115.7+ KB

None

In [26]:
new_df['Size']

0      170781696
1      261573632
2       52657152
3      218086400
4      366343168
         ...
995     49008640
996    107270144
997    160053248
998     46461952
999    378426368
Name: Size, Length: 971, dtype: object

In [27]:
# Convert 'Size' to numeric, coercing errors
new_df['Size'] = pd.to_numeric(new_df['Size'], errors='coerce')

# Convert bytes to kilobytes and rename the column
new_df['Size(kb)'] = new_df['Size'] / 1024

# Drop the original 'Size' column
new_df = new_df.drop('Size', axis=1)

# Display the updated DataFrame info and the first few rows
display(new_df.info())
display(new_df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 971 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               971 non-null    object
 1   Genres            971 non-null    object
 2   Content Rating    971 non-null    object
 3   Required Version  971 non-null    object
 4   Last Updated      971 non-null    object
 5   Current Version   971 non-null    object
 6   Price($)          971 non-null    float64
 7   Rating            971 non-null    float64
 8   Reviews           971 non-null    int64
 9   Size(kb)          971 non-null    float64
dtypes: float64(3), int64(1), object(6)
memory usage: 115.7+ KB

None

,App,Genres,Content Rating,Required Version,Last Updated,Current Version,Price($),Rating,Reviews,Size(kb)
0,Graphic Design & Logo Creator,"Graphics & Design, Photo & Video",4+,17.0,2025-09-25T13:46:19Z,12.9,0.0,4.51858,8581,166779.0
1,Smartist: Art Preview on Wall,"Photo & Video, Graphics & Design",4+,16.0,2025-09-07T16:55:25Z,1.6.10,0.0,4.77596,8320,255443.0
2,Nail Designs - Manicures & Art,"Lifestyle, Entertainment",4+,18.5,2025-08-27T15:58:43Z,5.02,0.0,3.95838,2499,51423.0
3,Tenada: Photo & Graphic Design,"Graphics & Design, Photo & Video",4+,14.0,2025-09-09T05:20:41Z,5.4.9,0.0,4.77688,1479,212975.0
4,Sketch Pro: Draw & Create Art,"Graphics & Design, Productivity",4+,13.0,2025-09-26T07:15:46Z,2.0.1,0.0,4.71448,6511,357757.0

In [28]:
new_df['Required Version'] = pd.to_numeric(new_df['Required Version'], errors='coerce')

# Display the updated DataFrame info to check the data type
display(new_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 971 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               971 non-null    object
 1   Genres            971 non-null    object
 2   Content Rating    971 non-null    object
 3   Required Version  967 non-null    float64
 4   Last Updated      971 non-null    object
 5   Current Version   971 non-null    object
 6   Price($)          971 non-null    float64
 7   Rating            971 non-null    float64
 8   Reviews           971 non-null    int64
 9   Size(kb)          971 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 115.7+ KB

None

In [31]:
new_df['Last Updated'] = pd.to_datetime(new_df['Last Updated'], errors='coerce').dt.tz_convert(None)

# Display the updated DataFrame info to check the data type
display(new_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 971 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               971 non-null    object
 1   Genres            971 non-null    object
 2   Content Rating    971 non-null    object
 3   Required Version  967 non-null    float64
 4   Last Updated      971 non-null    datetime64[ns]
 5   Current Version   971 non-null    object
 6   Price($)          971 non-null    float64
 7   Rating            971 non-null    float64
 8   Reviews           971 non-null    int64
 9   Size(kb)          971 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 115.7+ KB

None

In [34]:
display(new_df['Last Updated'].dt.date)

0      2025-09-25
1      2025-09-07
2      2025-08-27
3      2025-09-09
4      2025-09-26
          ...
995    2025-09-18
996    2025-09-12
997    2025-09-19
998    2025-08-14
999    2022-08-18
Name: Last Updated, Length: 971, dtype: object

In [36]:
new_df['Last Updated'] = pd.to_datetime(new_df['Last Updated']).dt.normalize()

# Display the updated DataFrame info to confirm the data type change
display(new_df.info())
display(new_df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 971 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               971 non-null    object
 1   Genres            971 non-null    object
 2   Content Rating    971 non-null    object
 3   Required Version  967 non-null    float64
 4   Last Updated      971 non-null    datetime64[ns]
 5   Current Version   971 non-null    object
 6   Price($)          971 non-null    float64
 7   Rating            971 non-null    float64
 8   Reviews           971 non-null    int64
 9   Size(kb)          971 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 115.7+ KB

None

,App,Genres,Content Rating,Required Version,Last Updated,Current Version,Price($),Rating,Reviews,Size(kb)
0,Graphic Design & Logo Creator,"Graphics & Design, Photo & Video",4+,17.0,2025-09-25,12.9,0.0,4.51858,8581,166779.0
1,Smartist: Art Preview on Wall,"Photo & Video, Graphics & Design",4+,16.0,2025-09-07,1.6.10,0.0,4.77596,8320,255443.0
2,Nail Designs - Manicures & Art,"Lifestyle, Entertainment",4+,18.5,2025-08-27,5.02,0.0,3.95838,2499,51423.0
3,Tenada: Photo & Graphic Design,"Graphics & Design, Photo & Video",4+,14.0,2025-09-09,5.4.9,0.0,4.77688,1479,212975.0
4,Sketch Pro: Draw & Create Art,"Graphics & Design, Productivity",4+,13.0,2025-09-26,2.0.1,0.0,4.71448,6511,357757.0

In [39]:
new_df = new_df.reset_index(drop=True)
display(new_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 971 entries, 0 to 970
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   App               971 non-null    object
 1   Genres            971 non-null    object
 2   Content Rating    971 non-null    object
 3   Required Version  967 non-null    float64
 4   Last Updated      971 non-null    datetime64[ns]
 5   Current Version   971 non-null    object
 6   Price($)          971 non-null    float64
 7   Rating            971 non-null    float64
 8   Reviews           971 non-null    int64
 9   Size(kb)          971 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 76.0+ KB

None

In [40]:
from google.colab import files

# Specify the filename for the downloaded CSV
filename = 'rapidAPIdataframe.csv'

# Convert the DataFrame to a CSV file
new_df.to_csv(filename, index=False)

# Download the file
files.download(filename)