In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('googleplaystore.csv')

In [4]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [5]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [6]:
# Check for missing values
print("Missing values per column:")
display(df.isnull().sum())

Missing values per column:

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [7]:
print("Rows with missing Rating values:")
display(df[df['Rating'].isnull()])

Rows with missing Rating values:

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
23,Mcqueen Coloring pages,ART_AND_DESIGN,NaN,61,7.0M,"100,000+",Free,0,Everyone,Art & Design;Action & Adventure,"March 7, 2018",1.0.0,4.1 and up
113,Wrinkles and rejuvenation,BEAUTY,NaN,182,5.7M,"100,000+",Free,0,Everyone 10+,Beauty,"September 20, 2017",8.0,3.0 and up
123,Manicure - nail design,BEAUTY,NaN,119,3.7M,"50,000+",Free,0,Everyone,Beauty,"July 23, 2018",1.3,4.1 and up
126,Skin Care and Natural Beauty,BEAUTY,NaN,654,7.4M,"100,000+",Free,0,Teen,Beauty,"July 17, 2018",1.15,4.1 and up
129,"Secrets of beauty, youth and health",BEAUTY,NaN,77,2.9M,"10,000+",Free,0,Mature 17+,Beauty,"August 8, 2017",2.0,2.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10824,Cardio-FR,MEDICAL,NaN,67,82M,"10,000+",Free,0,Everyone,Medical,"July 31, 2018",2.2.2,4.4 and up
10825,Naruto & Boruto FR,SOCIAL,NaN,7,7.7M,100+,Free,0,Teen,Social,"February 2, 2018",1.0,4.0 and up
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9.8M,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up

In [8]:
print("Duplicate rows based on 'App' column:")
app_duplicates = df[df.duplicated(subset=['App'], keep=False)]
print("Number of duplicate rows based on 'App' column:", len(app_duplicates))
display(app_duplicates.sort_values(by='App'))

Duplicate rows based on 'App' column:
Number of duplicate rows based on 'App' column: 1979

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1393,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3.8M,"500,000+",Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
1407,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490,3.8M,"500,000+",Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
2543,1800 Contacts - Lens Store,MEDICAL,4.7,23160,26M,"1,000,000+",Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up
2322,1800 Contacts - Lens Store,MEDICAL,4.7,23160,26M,"1,000,000+",Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up
2385,2017 EMRA Antibiotic Guide,MEDICAL,4.4,12,3.8M,"1,000+",Paid,$16.99,Everyone,Medical,"January 27, 2017",1.0.5,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3202,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848,Varies with device,"50,000,000+",Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
3118,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848,Varies with device,"50,000,000+",Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
3103,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848,Varies with device,"50,000,000+",Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
8291,wetter.com - Weather and Radar,WEATHER,4.2,189310,38M,"10,000,000+",Free,0,Everyone,Weather,"August 6, 2018",Varies with device,Varies with device
3652,wetter.com - Weather and Radar,WEATHER,4.2,189313,38M,"10,000,000+",Free,0,Everyone,Weather,"August 6, 2018",Varies with device,Varies with device

In [9]:
count_10_best_foods = len(df[df['App'] == '10 Best Foods for You'])
print(f"Number of apps with the name '10 Best Foods for You': {count_10_best_foods}")

Number of apps with the name '10 Best Foods for You': 2

In [11]:
count_trivago = len(df[df['App'] == 'trivago: Hotels & Travel'])
print(f"Number of apps with the name 'trivago: Hotels & Travel': {count_trivago}")

Number of apps with the name 'trivago: Hotels & Travel': 3

In [12]:
df.drop_duplicates(subset=['App'], keep='first', inplace=True)
print("Number of rows after removing duplicates based on 'App' column:", len(df))

Number of rows after removing duplicates based on 'App' column: 9660

In [13]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [14]:
count_10_best_foods = len(df[df['App'] == '10 Best Foods for You'])
print(f"Number of apps with the name '10 Best Foods for You': {count_10_best_foods}")

Number of apps with the name '10 Best Foods for You': 1

In [15]:
print("Data type of 'Reviews' column:", df['Reviews'].dtype)

Data type of 'Reviews' column: object

In [16]:
print("First 20 unique values in 'Reviews' column:")
display(df['Reviews'].unique()[:20])

First 20 unique values in 'Reviews' column:

array(['159', '967', '87510', '215644', '167', '178', '36815', '13791',
       '121', '13880', '8788', '44829', '4326', '1518', '55', '3632',
       '27', '194216', '224399', '450'], dtype=object)

In [17]:
# Attempt to convert 'Reviews' to numeric, coercing errors to NaN
df['Reviews_numeric'] = pd.to_numeric(df['Reviews'], errors='coerce')

# Find rows where the conversion resulted in NaN (i.e., the original value was not numeric)
non_integer_reviews = df[df['Reviews_numeric'].isnull()]

print("Entries in 'Reviews' column that are not integers:")
display(non_integer_reviews[['App', 'Reviews']])

Entries in 'Reviews' column that are not integers:

                                           App Reviews
10472  Life Made WI-Fi Touchscreen Photo Frame    3.0M

In [18]:
# Replace '3.0M' with 3000000 in the original 'Reviews' column
df['Reviews'] = df['Reviews'].replace('3.0M', '3000000')

# Convert 'Reviews' to numeric, coercing errors to NaN
df['Reviews_numeric'] = pd.to_numeric(df['Reviews'], errors='coerce')

# Convert the numeric column to integer, allowing for potential NaNs
df['Reviews_numeric'] = df['Reviews_numeric'].astype('Int64') # Use 'Int64' for nullable integer

# Find rows where the conversion resulted in NaN (i.e., the original value was not numeric)
non_integer_reviews_after_conversion = df[df['Reviews_numeric'].isnull()]

print("Entries in 'Reviews' column that are not integers after conversion:")
display(non_integer_reviews_after_conversion[['App', 'Reviews']])

print("\nData type of 'Reviews_numeric' column after conversion:")
print(df['Reviews_numeric'].dtype)

Entries in 'Reviews' column that are not integers after conversion:

Empty DataFrame
Columns: [App, Reviews]
Index: []

Data type of 'Reviews_numeric' column after conversion:
Int64

In [19]:
print("Data type of 'Reviews' column:", df['Reviews'].dtype)

Data type of 'Reviews' column: object

In [21]:
print("Value of 'Reviews' at index 10472:", df.loc[10472, 'Reviews'])

Value of 'Reviews' at index 10472: 3000000

In [22]:
value_at_10472 = df.loc[10472, 'Reviews']
print(f"Value at index 10472 in 'Reviews': {value_at_10472}")
print(f"Data type of the value: {type(value_at_10472)}")

Value at index 10472 in 'Reviews': 3000000
Data type of the value: <class 'str'>

In [23]:
value_at_10471 = df.loc[10471, 'Reviews']
print(f"Value at index 10471 in 'Reviews': {value_at_10471}")
print(f"Data type of the value: {type(value_at_10471)}")

Value at index 10471 in 'Reviews': 1042
Data type of the value: <class 'str'>

In [24]:
# Store the original 'Reviews' column as a separate Series
original_reviews_series = df['Reviews'].copy()

# Drop the original 'Reviews' column from df
df = df.drop('Reviews', axis=1)

# Rename the 'Reviews_numeric' column to 'Reviews'
df = df.rename(columns={'Reviews_numeric': 'Reviews'})

print("\nData type of the new 'Reviews' column in df:")
display(df['Reviews'].dtype)
print("\nFirst 5 values in the new 'Reviews' column in df:")
display(df['Reviews'].head())

Data type of the new 'Reviews' column in df:

Int64Dtype()

First 5 values in the new 'Reviews' column in df:

0       159
1       967
2     87510
3    215644
4       967
Name: Reviews, dtype: Int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9660 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9660 non-null   object
 2   Rating          8197 non-null   float64
 3   Size            9660 non-null   object
 4   Installs        9660 non-null   object
 5   Type            9659 non-null   object
 6   Price           9660 non-null   object
 7   Content Rating  9659 non-null   object
 8   Genres          9660 non-null   object
 9   Last Updated    9660 non-null   object
 10  Current Ver     9652 non-null   object
 11  Android Ver     9657 non-null   object
 12  Reviews         9660 non-null   Int64
dtypes: Int64(1), float64(1), object(11)
memory usage: 1.3+ MB

In [26]:
df

,App,Category,Rating,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159
1,Coloring book moana,ART_AND_DESIGN,3.9,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,38
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4
10838,Parkinson Exercices FR,MEDICAL,NaN,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,3
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,114
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,398307

In [27]:
# Count entries in 'Price' that are not '0' and contain '$'
price_with_dollar_sign = df[df['Price'].str.contains('$', na=False) & (df['Price'] != '0')]

print(f"Number of entries in 'Price' with a dollar sign (excluding '0'): {len(price_with_dollar_sign)}")

Number of entries in 'Price' with a dollar sign (excluding '0'): 757

In [28]:
# Rename the 'Price' column to 'Price($)'
df = df.rename(columns={'Price': 'Price($)'})

# Remove the '$' sign from the 'Price($)' column
df['Price($)'] = df['Price($)'].str.replace('$', '', regex=False)

# Convert the 'Price($)' column to float64
df['Price($)'] = pd.to_numeric(df['Price($)'], errors='coerce')

print("Data type of the 'Price($)' column after conversion:")
display(df['Price($)'].dtype)
print("\nFirst 5 values in the 'Price($)' column after cleaning:")
display(df['Price($)'].head())

Data type of the 'Price($)' column after conversion:

dtype('float64')

First 5 values in the 'Price($)' column after cleaning:

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Price($), dtype: float64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9660 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9660 non-null   object
 2   Rating          8197 non-null   float64
 3   Size            9660 non-null   object
 4   Installs        9660 non-null   object
 5   Type            9659 non-null   object
 6   Price($)        9659 non-null   float64
 7   Content Rating  9659 non-null   object
 8   Genres          9660 non-null   object
 9   Last Updated    9660 non-null   object
 10  Current Ver     9652 non-null   object
 11  Android Ver     9657 non-null   object
 12  Reviews         9660 non-null   Int64
dtypes: Int64(1), float64(2), object(10)
memory usage: 1.3+ MB

In [30]:
print("Row with missing 'Price($)' value:")
display(df[df['Price($)'].isnull()])

Row with missing 'Price($)' value:

,App,Category,Rating,Size,Installs,Type,Price($),Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,"1,000+",Free,0,NaN,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,3000000

In [31]:
df['Price($)'] = df['Price($)'].fillna(0)

print("Number of missing values in 'Price($)' after filling:")
display(df['Price($)'].isnull().sum())

Number of missing values in 'Price($)' after filling:

np.int64(0)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9660 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9660 non-null   object
 2   Rating          8197 non-null   float64
 3   Size            9660 non-null   object
 4   Installs        9660 non-null   object
 5   Type            9659 non-null   object
 6   Price($)        9660 non-null   float64
 7   Content Rating  9659 non-null   object
 8   Genres          9660 non-null   object
 9   Last Updated    9660 non-null   object
 10  Current Ver     9652 non-null   object
 11  Android Ver     9657 non-null   object
 12  Reviews         9660 non-null   Int64
dtypes: Int64(1), float64(2), object(10)
memory usage: 1.3+ MB

In [33]:
df = df.reset_index(drop=True)

print("DataFrame info after resetting index:")
display(df.info())

DataFrame info after resetting index:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9660 entries, 0 to 9659
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9660 non-null   object
 2   Rating          8197 non-null   float64
 3   Size            9660 non-null   object
 4   Installs        9660 non-null   object
 5   Type            9659 non-null   object
 6   Price($)        9660 non-null   float64
 7   Content Rating  9659 non-null   object
 8   Genres          9660 non-null   object
 9   Last Updated    9660 non-null   object
 10  Current Ver     9652 non-null   object
 11  Android Ver     9657 non-null   object
 12  Reviews         9660 non-null   Int64
dtypes: Int64(1), float64(2), object(10)
memory usage: 990.7+ KB

None

In [34]:
df

,App,Category,Rating,Size,Installs,Type,Price($),Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159
1,Coloring book moana,ART_AND_DESIGN,3.9,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9655,Sya9a Maroc - FR,FAMILY,4.5,53M,"5,000+",Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,38
9656,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,3.6M,100+,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4
9657,Parkinson Exercices FR,MEDICAL,NaN,9.5M,"1,000+",Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,3
9658,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,Varies with device,"1,000+",Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,114
9659,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,19M,"10,000,000+",Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,398307

In [35]:
print("First 20 unique values in 'Last Updated' column:")
display(df['Last Updated'].unique()[:20])

First 20 unique values in 'Last Updated' column:

array(['January 7, 2018', 'January 15, 2018', 'August 1, 2018',
       'June 8, 2018', 'June 20, 2018', 'March 26, 2017',
       'April 26, 2018', 'June 14, 2018', 'September 20, 2017',
       'July 3, 2018', 'October 27, 2017', 'July 31, 2018',
       'April 2, 2018', 'June 26, 2018', 'August 3, 2018', 'June 6, 2018',
       'November 7, 2017', 'July 30, 2018', 'April 20, 2018',
       'March 20, 2018'], dtype=object)

In [40]:
print("\nAttempting to convert 'Last Updated' to datetime:")
try:
    df['Last Updated'] = pd.to_datetime(df['Last Updated'])
    print("Conversion successful!")
    print("\nData type of 'Last Updated' after conversion:")
    display(df['Last Updated'].dtype)
except Exception as e:
    print(f"Error during conversion: {e}")
    print("There might be anomalies in the date format.")

Attempting to convert 'Last Updated' to datetime:
Error during conversion: time data "1.0.19" doesn't match format "%B %d, %Y", at position 1348. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
There might be anomalies in the date format.

In [38]:
display(df.loc[1348])

App               Bed Time Fan - White Noise Sleep Sounds
Category                                        LIFESTYLE
Rating                                                4.5
Size                                                 7.5M
Installs                                         500,000+
Type                                                 Free
Price($)                                              0.0
Content Rating                                   Everyone
Genres                                          Lifestyle
Last Updated                               April 26, 2018
Current Ver                                           1.2
Android Ver                                    4.0 and up
Reviews                                             10097
Name: 1348, dtype: object

In [39]:
display(df['Last Updated'])

0        January 7, 2018
1       January 15, 2018
2         August 1, 2018
3           June 8, 2018
4          June 20, 2018
              ...
9655       July 25, 2017
9656        July 6, 2018
9657    January 20, 2017
9658    January 19, 2015
9659       July 25, 2018
Name: Last Updated, Length: 9660, dtype: object

In [41]:
df['Last Updated in datetime'] = pd.to_datetime(df['Last Updated'], errors='coerce')

print("Data type of the new 'Last Updated in datetime' column:")
display(df['Last Updated in datetime'].dtype)
print("\nFirst 5 values in the new 'Last Updated in datetime' column:")
display(df['Last Updated in datetime'].head())
print("\nNumber of NaT values in the new 'Last Updated in datetime' column:")
display(df['Last Updated in datetime'].isnull().sum())

Data type of the new 'Last Updated in datetime' column:

dtype('<M8[ns]')

First 5 values in the new 'Last Updated in datetime' column:

0   2018-01-07
1   2018-01-15
2   2018-08-01
3   2018-06-08
4   2018-06-20
Name: Last Updated in datetime, dtype: datetime64[ns]

Number of NaT values in the new 'Last Updated in datetime' column:

np.int64(1)

In [42]:
print("Row with NaT value in 'Last Updated in datetime':")
display(df[df['Last Updated in datetime'].isnull()])

Row with NaT value in 'Last Updated in datetime':

,App,Category,Rating,Size,Installs,Type,Price($),Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews,Last Updated in datetime
9300,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,"1,000+",Free,0,0.0,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,3000000,NaT

In [43]:
# Modify the specified values in row 9300
df.loc[9300, 'Category'] = pd.NA # Set Category to pandas' missing value representation
df.loc[9300, 'Rating'] = 1.9
df.loc[9300, 'Size'] = '19.0'  # Keeping as string as per request
df.loc[9300, 'Installs'] = '1000+' # Keeping as string as per request
df.loc[9300, 'Type'] = 'Free'
df.loc[9300, 'Genres'] = pd.NA # Set Genres to pandas' missing value representation
df.loc[9300, 'Last Updated'] = 'February 11, 2018' # Keeping as string as per request
df.loc[9300, 'Last Updated in datetime'] = pd.to_datetime('2018-02-11')

# Display the modified row to confirm the changes
print("Row 9300 after modifications:")
display(df.loc[9300])

Row 9300 after modifications:

App                         Life Made WI-Fi Touchscreen Photo Frame
Category                                                       <NA>
Rating                                                          1.9
Size                                                           19.0
Installs                                                      1000+
Type                                                           Free
Price($)                                                        0.0
Content Rating                                                  NaN
Genres                                                         <NA>
Last Updated                                      February 11, 2018
Current Ver                                              4.0 and up
Android Ver                                                     NaN
Reviews                                                     3000000
Last Updated in datetime                        2018-02-11 00:00:00
Name: 9300, dtype: object

In [44]:
df

,App,Category,Rating,Size,Installs,Type,Price($),Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews,Last Updated in datetime
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,19M,"10,000+",Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159,2018-01-07
1,Coloring book moana,ART_AND_DESIGN,3.9,14M,"500,000+",Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967,2018-01-15
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,8.7M,"5,000,000+",Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510,2018-08-01
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,25M,"50,000,000+",Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644,2018-06-08
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,2.8M,"100,000+",Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967,2018-06-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9655,Sya9a Maroc - FR,FAMILY,4.5,53M,"5,000+",Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,38,2017-07-25
9656,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,3.6M,100+,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4,2018-07-06
9657,Parkinson Exercices FR,MEDICAL,NaN,9.5M,"1,000+",Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,3,2017-01-20
9658,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,Varies with device,"1,000+",Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,114,2015-01-19
9659,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,19M,"10,000,000+",Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,398307,2018-07-25

In [45]:
# Drop the original 'Last Updated' column
df = df.drop('Last Updated', axis=1)

# Rename 'Last Updated in datetime' to 'Last Updated'
df = df.rename(columns={'Last Updated in datetime': 'Last Updated'})

print("DataFrame columns after changes:")
display(df.columns)
print("\nData type of the new 'Last Updated' column:")
display(df['Last Updated'].dtype)

DataFrame columns after changes:

Index(['App', 'Category', 'Rating', 'Size', 'Installs', 'Type', 'Price($)',
       'Content Rating', 'Genres', 'Current Ver', 'Android Ver', 'Reviews',
       'Last Updated'],
      dtype='object')

Data type of the new 'Last Updated' column:

dtype('<M8[ns]')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9660 entries, 0 to 9659
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8197 non-null   float64
 3   Size            9660 non-null   object
 4   Installs        9660 non-null   object
 5   Type            9659 non-null   object
 6   Price($)        9660 non-null   float64
 7   Content Rating  9659 non-null   object
 8   Genres          9659 non-null   object
 9   Current Ver     9652 non-null   object
 10  Android Ver     9657 non-null   object
 11  Reviews         9660 non-null   Int64
 12  Last Updated    9660 non-null   datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(2), object(9)
memory usage: 990.7+ KB

In [50]:
print("First 50 unique values in 'Installs' column:")
display(df['Installs'].unique()[:50])

First 50 unique values in 'Installs' column:

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', '1000+'], dtype=object)

In [51]:
# Remove ',' and '+' from the 'Installs' column
df['Installs'] = df['Installs'].str.replace(',', '', regex=False).str.replace('+', '', regex=False)

# Convert the 'Installs' column to numeric (integer)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

print("Data type of the 'Installs' column after cleaning:")
display(df['Installs'].dtype)
print("\nFirst 5 values in the 'Installs' column after cleaning:")
display(df['Installs'].head())
print("\nNumber of missing values in 'Installs' after cleaning:")
display(df['Installs'].isnull().sum())

Data type of the 'Installs' column after cleaning:

dtype('int64')

First 5 values in the 'Installs' column after cleaning:

0       10000
1      500000
2     5000000
3    50000000
4      100000
Name: Installs, dtype: int64

Number of missing values in 'Installs' after cleaning:

np.int64(0)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9660 entries, 0 to 9659
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8197 non-null   float64
 3   Size            9660 non-null   object
 4   Installs        9660 non-null   int64
 5   Type            9659 non-null   object
 6   Price($)        9660 non-null   float64
 7   Content Rating  9659 non-null   object
 8   Genres          9659 non-null   object
 9   Current Ver     9652 non-null   object
 10  Android Ver     9657 non-null   object
 11  Reviews         9660 non-null   Int64
 12  Last Updated    9660 non-null   datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 990.7+ KB

In [54]:
print("Rows where 'Size' is '19.0':")
display(df[df['Size'] == '19.0'])

Rows where 'Size' is '19.0':

,App,Category,Rating,Size,Installs,Type,Price($),Content Rating,Genres,Current Ver,Android Ver,Reviews,Last Updated
9300,Life Made WI-Fi Touchscreen Photo Frame,<NA>,1.9,19.0,1000,Free,0.0,NaN,<NA>,4.0 and up,NaN,3000000,2018-02-11

In [55]:
# Replace '19.0' with NaN in the 'Size' column
df['Size'] = df['Size'].replace('19.0', pd.NA)

print("Rows where 'Size' is now NaN:")
display(df[df['Size'].isnull()])

Rows where 'Size' is now NaN:

,App,Category,Rating,Size,Installs,Type,Price($),Content Rating,Genres,Current Ver,Android Ver,Reviews,Last Updated
9300,Life Made WI-Fi Touchscreen Photo Frame,<NA>,1.9,<NA>,1000,Free,0.0,NaN,<NA>,4.0 and up,NaN,3000000,2018-02-11

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9660 entries, 0 to 9659
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9660 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8197 non-null   float64
 3   Size            9659 non-null   object
 4   Installs        9660 non-null   int64
 5   Type            9659 non-null   object
 6   Price($)        9660 non-null   float64
 7   Content Rating  9659 non-null   object
 8   Genres          9659 non-null   object
 9   Current Ver     9652 non-null   object
 10  Android Ver     9657 non-null   object
 11  Reviews         9660 non-null   Int64
 12  Last Updated    9660 non-null   datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 990.7+ KB

In [57]:
df

,App,Category,Rating,Size,Installs,Type,Price($),Content Rating,Genres,Current Ver,Android Ver,Reviews,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,19M,10000,Free,0.0,Everyone,Art & Design,1.0.0,4.0.3 and up,159,2018-01-07
1,Coloring book moana,ART_AND_DESIGN,3.9,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2.0.0,4.0.3 and up,967,2018-01-15
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,8.7M,5000000,Free,0.0,Everyone,Art & Design,1.2.4,4.0.3 and up,87510,2018-08-01
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,25M,50000000,Free,0.0,Teen,Art & Design,Varies with device,4.2 and up,215644,2018-06-08
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,1.1,4.4 and up,967,2018-06-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9655,Sya9a Maroc - FR,FAMILY,4.5,53M,5000,Free,0.0,Everyone,Education,1.48,4.1 and up,38,2017-07-25
9656,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,3.6M,100,Free,0.0,Everyone,Education,1.0,4.1 and up,4,2018-07-06
9657,Parkinson Exercices FR,MEDICAL,NaN,9.5M,1000,Free,0.0,Everyone,Medical,1.0,2.2 and up,3,2017-01-20
9658,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,Varies with device,1000,Free,0.0,Mature 17+,Books & Reference,Varies with device,Varies with device,114,2015-01-19
9659,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,19M,10000000,Free,0.0,Everyone,Lifestyle,Varies with device,Varies with device,398307,2018-07-25

In [58]:
df.to_csv('cleaned_googleplaystore.csv', index=False)